"""
AAS Client (Event-Driven Bridge from OPC UA to BaSyx)

What this program does (in simple terms):
- It connects to a machine's OPC UA server.
- It listens for specific machine/job events.
- When a matching event arrives, it extracts relevant job information.
- It sends that information to create/update an Asset Administration Shell (AAS)
    representation via the BaSyx APIs.

Why this is useful:
- OPC UA is used by machines to expose data and events.
- AAS is a standardized digital representation of an asset (for example, a machine
    or a job) so IT systems can consume it consistently.
- This script acts as a translator/bridge: machine events in, AAS updates out.

High-level flow:
1) Connect to OPC UA (`UA_ENDPOINT_URL`).
2) Resolve namespaces and navigate to the machine's `JobOrderResults` node.
3) Find the event type generated by that node.
4) Subscribe to those events (server-side filtered).
5) Put incoming events into an async queue.
6) Process queued events and map fields into `job_data`.
7) Call `create_aas_for_job(...)` to publish/update AAS data in BaSyx.

Configuration:
- All runtime settings (server URLs, node id, timing) come from `config.py`
    and can be overridden through environment variables.
"""

import sys
import asyncio
from asyncua import Client, Node, ua
from asyncua.common.events import Event
from common.helper import make_nodeid_string, variant_to_json_serializable
from ua_job_aas import create_aas_for_job
from ua_machine_aas import create_aas_for_identification

from config import UA_ENDPOINT_URL, UA_REQUEST_TIMEOUT, UA_MACHINE_INSTANCE_NODEID, UA_PUBLISHING_INTERVAL

EVENT_QUEUE: asyncio.Queue[Event] = asyncio.Queue(100)
EVENT_TYPE_NODEID: str | None = None
EVENT_TYPE_DISPLAYNAME: str | None = None


class SubscriptionHandler:
    """
    The SubscriptionHandler is used to handle the data that is received for the subscription.
    """

    async def event_notification(self, event: Event):
        """
        Callback for asyncua Subscription.
        This method will be called when the Client received an event message from the Server.
        """
        await EVENT_QUEUE.put(event)

    async def datachange_notification(self, node: Node, val, data):
        """
        Callback for asyncua Subscription.
        This method will be called when the Client received a data change message from the Server.
        We use this to detect if the subscription is still alive, as some OPC UA
        Servers may silently drop subscriptions after some time.
        """
        # print(f"DataChange Notification - Node: {node}, Value: {val}, Data: {data}")

    async def status_change_notification(self, status):
        """
        Callback for asyncua Subscription.
        This method will be called when the Client received a status change message from the Server.
        We can use this to detect if the subscription is still alive or if there are any issues with the connection.
        """
        print(f"Subscription Status Change: {status}")


async def process_event(eventtype_nodeid: str | None = None, eventtype_displayname: str | None = None):
    """Process one queued OPC UA event and forward matching JobOrder events to AAS creation."""
    event = await EVENT_QUEUE.get()
    if event is None:
        return
    # Keep this check even with server-side filtering as a defensive guard
    # against misconfigured filters or server-side model changes.
    if event.EventType.to_string() == eventtype_nodeid:
        print(f"Received new Event of type: {eventtype_displayname} [{event.EventType.to_string()}] processing...")
        await create_aas_for_job(event.get_event_props_as_fields_dict())
        return

    print(f"Received other event type, ignoring... EventType: {event.EventType.to_string()}")
    return


def exit_main():
    """Callback for asyncua Client connection loss. """
    sys.exit(1)


async def main():  # pylint: disable=too-many-statements
    """Connect to OPC UA, subscribe to events, and continuously process event queue entries."""
    client = Client(url=UA_ENDPOINT_URL, timeout=UA_REQUEST_TIMEOUT)
    client.application_uri = "urn:ua4machinery2aas-client"
    client.connection_lost_callback = exit_main
    await client.connect()
    print(f"Connected to OPC UA Server at {UA_ENDPOINT_URL}")

    # Load custom structure/type metadata so event payload fields can be
    # deserialized into typed Python objects instead of opaque Variants.
    await client.load_data_type_definitions()  # OPC UA v1.04 Structures
    await client.load_type_definitions()  # OPC UA v1.03 Structures

    namespace_array = await client.get_namespace_array()
    print(f"Namespace Array: {namespace_array}")

    di_index = namespace_array.index("http://opcfoundation.org/UA/DI/")
    print(f"Found OPC for DI namespace with index: {di_index}")
    machinery_index = namespace_array.index("http://opcfoundation.org/UA/Machinery/")
    print(f"Found OPC for Machinery namespace with index: {machinery_index}")
    machinery_jobs_index = namespace_array.index("http://opcfoundation.org/UA/Machinery/Jobs/")
    print(f"Found OPC for Machinery Jobs namespace with index: {machinery_jobs_index}")

    # Normalize configured NodeId/ExpandedNodeId (including nsu=...) into a
    # concrete NodeId string with namespace index for this server session.
    machine_nodeid = make_nodeid_string(UA_MACHINE_INSTANCE_NODEID, namespace_array)
    machine_node: Node = client.get_node(machine_nodeid)
    machine_displayname = await machine_node.read_display_name()
    print(f"Found machine instance ({machine_nodeid}): {machine_displayname.Text}")

    identification_node: Node = await machine_node.get_child(f"{di_index}:Identification")
    identification_properties = await identification_node.get_properties()
    identification = {}
    for prop in identification_properties:
        prop_name = await prop.read_display_name()
        prop_value: ua.DataValue = await prop.read_data_value()
        identification[prop_name.Text] = variant_to_json_serializable(prop_value.Value)
    print(f"Read machine identification properties: {identification}")
    await create_aas_for_identification(machine_displayname.Text, identification)
    print("Created/Updated AAS for machine identification", UA_MACHINE_INSTANCE_NODEID, identification)

    building_blocks_node: Node = await machine_node.get_child(f"{machinery_index}:MachineryBuildingBlocks")
    print(f"Found OPC for Machinery BuildingBlocks node: {await building_blocks_node.read_display_name()}")

    job_manager_node: Node = await building_blocks_node.get_child(f"{machine_node.nodeid.NamespaceIndex}:JobManager")
    print(f"Found OPC for Machinery JobManager node: {await job_manager_node.read_display_name()}")

    job_order_results_node: Node = await job_manager_node.get_child(f"{machinery_jobs_index}:JobOrderResults")
    print(f"Found OPC for Machinery JobOrderResults node: {await job_order_results_node.read_display_name()}")

    references = await job_order_results_node.get_references(refs=ua.ObjectIds.GeneratesEvent)
    print(f"Found {len(references)} GeneratesEvent references from Machinery JobOrderResults node")
    if len(references) == 0:
        print("No GeneratesEvent reference found for Machinery JobOrderResults node, cannot subscribe to events!")
        return

    ref_des = references[0]
    event_type_nodeid = ref_des.NodeId.to_string()
    found_eventtype_node = client.get_node(event_type_nodeid)
    event_type_displayname: ua.LocalizedText = await found_eventtype_node.read_display_name()
    print(f"Using EventType-NodeId's: {event_type_displayname.Text} [{event_type_nodeid}] for subscription")

    handler = SubscriptionHandler()
    subscription = await client.create_subscription(period=UA_PUBLISHING_INTERVAL, handler=handler, publishing=True)
    await subscription.subscribe_events(
        sourcenode=job_order_results_node, evtypes=[found_eventtype_node], where_clause_generation=True
    )
    await subscription.subscribe_data_change(
        client.get_node(ua.ObjectIds.Server_ServerStatus_CurrentTime),
        ua.AttributeIds.Value,
        1,
        ua.MonitoringMode.Reporting,
        5000,  # 5 second sampling interval for the data change subscription, just to keep the subscription alive
    )
    while True:
        # Polling keeps the loop simple and aligns processing cadence with the
        # configured publishing interval.
        if EVENT_QUEUE.qsize() > 0:
            await process_event(event_type_nodeid, event_type_displayname.Text)
        else:
            await asyncio.sleep(UA_PUBLISHING_INTERVAL / 1000)  # Sleep for the publishing interval


if __name__ == "__main__":
    asyncio.run(main())
